package com.deathhit.myleetcodesolutions.base.enum_type

enum class Question {
    ADD_TWO_NUMBERS,
    CONTAINER_WITH_MOST_WATER,
    //todo INTEGER_TO_ROMAN,
    LONGEST_PALINDROMIC_SUBSTRING,
    LONGEST_SUBSTRING_WITHOUT_REPEATING_CHARACTERS,
    MEDIAN_OF_TWO_SORTED_ARRAYS,
    PALINDROME_NUMBER,
    REGULAR_EXPRESSION_MATCHING,
    REVERSE_INTEGER,
    STRING_TO_INTEGER_ATOI,
    TWO_SUM,
    ZIGZAG_CONVERSION
}